# Generated by Django 3.1.6 on 2021-03-09 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('message', models.CharField(blank=True, max_length=600)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
